version: "3.8"
services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopass123
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    volumes:
      - miniodata:/data

volumes:
  miniodata: