version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: miniouser
      POSTGRES_PASSWORD: miniopass
      POSTGRES_DB: miniodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopass
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata: